### ISSUE TITLE
Failed allocate memory

### ISSUE THREAD

**Issue by ErickFThomaz** [NootInc/NootedRed#101]
**Describe the bug**
I'm using macOs and during use it keeps freezing and crashing

**To Reproduce**
Using system
Watch screen share on discord
Take a screenshot
Watch youtube videos

**Screenshots**
![image](https://github.com/NootInc/NootedRed/assets/80769325/16aeaa48-7ab1-4a37-a2aa-deab892e8953)

**System Information:**
 - macOS Version: macOs Ventura 13.4
 - CPU: AMD Ryzen 7 5700G

**Additional context**
[syslog.txt](https://github.com/NootInc/NootedRed/files/11811942/syslog.txt)

**Comment by ErickFThomaz** [comment]
Thanks work here!

**Comment by ErickFThomaz** [comment]
Before o put in *boot-args* `-nredvcn`command, my chrome, discord and whatsapp there is a long time with a black or white screen before actually opening, I took a look at the logs and I am having the following errors:

If anyone have discord and can help me. DM me *erickfthz*

[discorderror.txt](https://github.com/NootInc/NootedRed/files/11828265/discorderror.txt)
[googleerror.txt](https://github.com/NootInc/NootedRed/files/11828266/googleerror.txt)
[whatsapperror.txt](https://github.com/NootInc/NootedRed/files/11828267/whatsapperror.txt)

**Comment by killingspree69** [comment]
@jalavoui what
