### ISSUE TITLE
i can't enable nootedred on macos catalina

### ISSUE THREAD

**Issue by Tang061022Tang** [NootInc/NootedRed#104]
I installed macOS 10.15.6 on my AMD laptop and set it up successfully without this kext.
But when i enabled this kext, the system couldn't be started and some times later it restarted.
CPU:Ryzen 5 3550H with Vega 8 graphics
macOS version:10.15.6
boot:opencore 0.9.3 with the latest version of NootedRed 1.0.0

**Comment by NyanCatTW1** [comment]
From README.md:
> Supports the entire Vega Raven ASIC family (Ryzen 1xxx (Athlon Silver/Gold) to 5xxx and 7x30 series), **from Big Sur to Sonoma.**

**Comment by Tang061022Tang** [comment]
But I saw it can support it in the latest project
![443A35B4-7EC7-44F6-B4E6-3E240C1802D6](https://github.com/NootInc/NootedRed/assets/104187262/6598bc44-b510-4ff0-9a14-3fb894bdd736)

**Comment by NyanCatTW1** [comment]
Mate, it haven't been merged for a reason; so far we've only gotten black screen and failure to start

**Comment by Tang061022Tang** [comment]
The same to me😓hope it can support 10.15 in the future
