### ISSUE TITLE
Issues when booting

### ISSUE THREAD

**Issue by gorouflex** [NootInc/NootedRed#105]
When i successfully install the macOs big sur and prepare to enable Nred for hardware acceleration but after i enable it not boot to my macOs 
Nred : https://github.com/NootInc/NootedRed/actions/runs/5256337475

Laptop (asus vivobook m413ia)
Macos bigsur 11.7.7
Amd ryzen 5 4500U

**Comment by gorouflex** [comment]
![image](https://github.com/NootInc/NootedRed/assets/98001973/31365dee-4c74-4d5a-84c1-6046e2ecc595)

**Comment by gorouflex** [comment]
I tried to reset nvram and sometimes it will boot into, but it's very rare...

**Comment by gorouflex** [comment]
![image](https://github.com/NootInc/NootedRed/assets/98001973/8927a472-89ca-4708-aaab-dfd62e7a028c)

This is the chance that i can boot without any issues but after rebooting it ư show up the error that i meantioned

**Comment by ChefKissInc** [comment]
Outdated build. Upgrade to latest "master" branch and reopen the issue if the problem persists.

**Comment by gorouflex** [comment]
I try the latest one and the error still appear 🤧

**Comment by ChefKissInc** [comment]
What "error"

**Comment by gorouflex** [comment]
![image](https://github.com/NootInc/NootedRed/assets/98001973/28f8366d-fc4d-45ac-8e0d-617e43f55505)
This...i have to try reset nvram many times to boot macOs without get stuck here

**Comment by ChefKissInc** [comment]
That's not related to NRed

**Comment by gorouflex** [comment]
Oh... can you check my current efi?

**Comment by gorouflex** [comment]
Ok tks for ur help
