### ISSUE TITLE
Browser Crashes and Freezes the system (except Safari)

### ISSUE THREAD

**Issue by ShioTP** [NootInc/NootedRed#109]
**Describe the bug**
The Browser crashes, and after that, it will freeze the whole system, making it unable to be used.

**To Reproduce**

**Expected behavior**
I hope soon that other browser won't crash and freeze the system. 

**Screenshots**

**System Information:**
 - macOS Version: macOS 13.4.1
 - CPU: AMD Ryzen 5 3400g

**Additional context**

**Comment by ShioTP** [comment]
> dup of #91 
Ohh my bad, imma close this then.

**Comment by nanocodium** [comment]
@ShioTP BOB
