### ISSUE TITLE
Renoir-based iGPUs (Ryzen 4XXX series and newer) do not work

### ISSUE THREAD

**Issue by ChefKissInc** [NootInc/NootedRed#11]
Renoir doesn't work at all. Reason unknown.

**Comment by dhr-uvin** [comment]
Hello.

I am a person whos been following this project for a while , mainly for renoir. The README doesnt mention if it will be fixed , so are attempts to fix it happening?

Thanks

**Comment by ChefKissInc** [comment]
@dhr-uvin If there was no intention to fix it, why would we mention it, even make an issue about it?
We’re not sure what the problem is, so fixing it has got a long way. The error is too vague to do anything with

**Comment by dhr-uvin** [comment]
> make

Sorry , just asking. Keep up the good work!

**Comment by akwangl** [comment]
Look forward to 5000 Series

**Comment by dockylf** [comment]
Looking forward to 6900hx

**Comment by ChefKissInc** [comment]
@jalavoui Interesting idea. We’ll try that on our next testing rounds, see where that leads

**Comment by ChefKissInc** [comment]
@jalavoui Seems to be the Accelerator specifically; it dies randomly while processing some SDMA commands that WindowServer sends early in initialisation. FB-only mode works, and the HWLibs themselves are unlikely to be causing the issue on their own

**Comment by danboeira** [comment]
Hello everyone, first I would like to thank you for your commitment to the development of this kext.
I would like to make myself available as a tester for the AMD Ryzen 5 4600G processor, with the Vega 7 (Ranoir) on my computer.
At the moment I will not be able to invest in a compatible GPU, and I would like to test this new kext on my computer.
So far, I haven't been able to boot as needed with the guidelines through the available ''read me''.
Thank you very much!!!

**Comment by hsnfirdaus** [comment]
I think this also affected Ryzen 5 5600G. I hope you can find a solution (for now using -nredfbonly boot flag "Partialy accelerated" work)!

**Comment by ChefKissInc** [comment]
@hsnfirdaus The title says 4XXX+…

**Comment by Berkan111111** [comment]
Will run amd ryzen 5 5500u processor

**Comment by akwangl** [comment]
> Will run amd ryzen 5 5500u processor

Don't dream，We can't do that yet

**Comment by PsaTyrE** [comment]
> I think this also affected Ryzen 5 5600G. I hope you can find a solution (for now using -nredfbonly boot flag "Partialy accelerated" work)!

can i ask for your efi file
