### ISSUE TITLE
A new repo to store binary files.

### ISSUE THREAD

**Issue by laobamac** [NootInc/NootedRed#110]
Hello, I am Laobamac, a hackintosh enthusiast. I hope to create a new repo to store the binary files compiled by NootedRed for ease of use only. I will not make any modifications to the source code, and all interpretation rights belong to NootInc. Please allow if it is possible.

**Comment by ChefKissInc** [comment]
@laobamac No, users can grab artefacts from the Actions tab by themselves just fine. This is beta software
