### ISSUE TITLE
Changing Device Property for VGA Compatible Controller will break Ventura 13.4.1

### ISSUE THREAD

**Issue by CraigHazan** [NootInc/NootedRed#117]
This verbose message was a result of changing the VGA compatible controller Device property in the EFI. 

![198B61D2-8E55-487C-B652-D121EC633553](https://github.com/NootInc/NootInc.github.io/assets/20331487/13f1ec75-cd26-4a0f-a846-b64543fcf816)
![Screenshot 2023-07-08 at 10 28 14 AM](https://github.com/NootInc/NootInc.github.io/assets/20331487/4f017279-2676-482b-bb63-bcee5f19b7e4)

**Comment by ChefKissInc** [comment]
So what do you mean @CraigHazan

**Comment by CraigHazan** [comment]
To change the GPU name for the About This Mac window you could add a device property to rename it in your EFI. A few days ago I had the verbose about failing to boot and I just replaced the EFI and booted to Desktop. Same thing happened again earlier, same verbose and failing to boot. removing the property fixed the problem.

**Comment by ChefKissInc** [comment]
Your English quality is making it hard to communicate. If you're using a translator, please switch to a different one.
Do you mean the `model` property?

**Comment by CraigHazan** [comment]
I'm from England, there's nothing wrong with my English. Correct the Model number, It says Renoir but about this Mac says AMD Radeon Graphics.

**Comment by ChefKissInc** [comment]
Residing in a certain country does not necessarily quantify the extent of your English knowledge.

**Comment by ChefKissInc** [comment]
(I still am unable to comprehend what you're trying to say, if you actually want me to resolve this, you will have to find a way to state more clearly your problem)

**Comment by devio10** [comment]
> Residing in a certain country does not necessarily quantify the extent of your English knowledge.

![image](https://github.com/NootInc/NootedRed/assets/64607085/6e7d419b-e37f-42fd-8596-d464f713fdb5)

**Comment by CraigHazan** [comment]
Nvm

**Comment by ChefKissInc** [comment]
Well, if you're trying to override the `model` property, NRed does not support that; it will overwrite it. But I don't know why that'd cause a panic.
But, okay then...

**Comment by ChefKissInc** [comment]
Uh... where?

**Comment by ChefKissInc** [comment]
@jalavoui Ah, I get it
