### ISSUE TITLE
Microphone not working on macOS

### ISSUE THREAD

**Issue by Geekmemz** [NootInc/NootedRed#118]
Describe the bug** My microphone is not working on macOS after using the noted red project to solve the AMD APU graphics driver issue. 1. Install the noted red project to solve the AMD APU graphics driver issue on macOS. 2. The graphics card is recognized normally and everything else is fine, but the microphone is not working. 3. My microphone is not connected to the regular sound card, it is connected to the AMD APU integrated graphics. 4. On Windows, if the graphics driver is not installed, this microphone cannot even be used. 5. On macOS, although the microphone is recognized, it cannot be used. 6. The only microphone that can be used in the settings is the Realtek sound card, but this microphone does not exist. **Expected behavior** I expected my microphone to work normally on macOS after using the noted red project to solve the AMD APU graphics driver issue.  **System Information:** - macOS Version: [macOS 12] - CPU: [AMD Ryzen  7 5700U] 
By the way，I am not a native English speaker, so I used AI to generate this. It may seem a bit confusing in logic, but overall I have checked it and there are no problems. I hope you can fix this issue, thank you.

**Comment by ChefKissInc** [comment]
That's not a NootedRed issue. Complain to Acidanthera for AppleALC lacking microphone support on AMD.
