### ISSUE TITLE
Latest version of NootedRed unable to enter login screen on macOS 12.5

### ISSUE THREAD

**Issue by Geekmemz** [NootInc/NootedRed#120]
**Describe the bug** My computer is running macOS 12.5 with an AMD Ryzen 7 5700U CPU. I was previously using an older version of NootedRed (around June 2023) and everything was working fine. However, after updating to the latest version, I encountered a problem. When I enable the -v option and run the code, the boot logo appears on the screen, but it gets stuck there and cannot enter the login screen. **To Reproduce** Steps to reproduce the behavior: 1. Update NootedRed to the latest version 2. Enable the -v option 3. Run the code 4. The boot logo appears on the screen, but it gets stuck there and cannot enter the login screen **Expected behavior** I hope this issue can be resolved so that the latest version of NootedRed can enter the login screen normally.  **System Information:** - macOS Version: macOS 12.5 - CPU: AMD Ryzen 7 5700U **Additional context** My OC version is 0.9.2. Thank you for your attention to this issue. I appreciate your help in resolving it.

**Comment by ChefKissInc** [comment]
Does the previous CI run work?

**Comment by Geekmemz** [comment]
yes

**Comment by ChefKissInc** [comment]
[NootedRed-1.0.0-DEBUG.zip](https://github.com/NootInc/NootedRed/files/12004531/NootedRed-1.0.0-DEBUG.zip)
@Geekmemz does this work?

**Comment by Geekmemz** [comment]
It can work, but I panicked when I ran the code with -v for the first time, but the second time I started up smoothly and finished the code. It got stuck on the Apple logo for about 10 seconds, but eventually it went in.

**Comment by ChefKissInc** [comment]
But does what I sent work

**Comment by Geekmemz** [comment]
I restarted it and it still panicked the first time. After restarting, it finished the code and got stuck on the Apple logo, but this time it has been stuck for 3 minutes and still hasn’t entered the login screen.

**Comment by Geekmemz** [comment]
By the way, during a recent accidental entry, I tried running the GPU test of Geekbench 6. The OpenCL test crashed directly, and the Metal test had no progress, but my computer would freeze for a long time.

**Comment by ChefKissInc** [comment]
[NootedRed-1.0.0-DEBUG.zip](https://github.com/NootInc/NootedRed/files/12010629/NootedRed-1.0.0-DEBUG.zip)
Does this work?

**Comment by Geekmemz** [comment]
It is still stuck on the Apple logo. Do you need me to send you my nootedred that I can use normally?

**Comment by Geekmemz** [comment]
Do you need me to send you my opencore EFI？

**Comment by ChefKissInc** [comment]
[NootedRed-1.0.0-DEBUG.zip](https://github.com/NootInc/NootedRed/files/12010752/NootedRed-1.0.0-DEBUG.zip)
Can you try this? @Geekmemz

**Comment by Geekmemz** [comment]
![168905162803288721394743217073](https://github.com/NootInc/NootedRed/assets/97420795/150b82ca-b5bc-4d81-ba9a-b56f2d593f52)
This is where it gets stuck after running the code with -v, this is not working anymore.

**Comment by ChefKissInc** [comment]
Are you sure you're not using something like `-nredvcn`

**Comment by Geekmemz** [comment]
Yes, I used -nredvcn, what is this for and do I need to disable it?

**Comment by ChefKissInc** [comment]
Uh... who told you to use it

**Comment by Geekmemz** [comment]
I forgot who told me, but I remember someone said that this thing can enable VDA hardware decoding, and turning it on and off does not have much impact.

**Comment by Geekmemz** [comment]
So is this option for enabling VDA hardware decoding? If so, why can’t it be turned on?

**Comment by ChefKissInc** [comment]
It is, but it's not complete. There is a reason it's gated behind an undocumented boot flag; it's WIP and will cause issues

**Comment by ChefKissInc** [comment]
This still shouldn't have happened, and I'm looking into it right now

**Comment by ChefKissInc** [comment]
In the meantime, try without the boot arg

**Comment by Geekmemz** [comment]
wait，let me try the newest kext

**Comment by ChefKissInc** [comment]
Don't. You presented the issue in a way that I thought something else was broken.
Try this one: 
[NootedRed-1.0.0-DEBUG.zip](https://github.com/NootInc/NootedRed/files/12010911/NootedRed-1.0.0-DEBUG.zip)

**Comment by Geekmemz** [comment]
What is the difference between the debug version and the release version?

**Comment by ChefKissInc** [comment]
<img width="1118" alt="Screenshot 2023-07-11 at 08 19 30" src="https://github.com/NootInc/NootedRed/assets/30368284/12e52421-b8bf-4e5c-8a3e-4e29547ad101">

**Comment by Geekmemz** [comment]
It works normally, but it has already stuttered in the GPU test of Geekbench 6.

**Comment by ChefKissInc** [comment]
Compute not working well is a known and different issue. Thanks for your cooperation in figuring out the issue with `-nredvcn`
