### ISSUE TITLE
Will it adapt to the 6800H processor in the future?

### ISSUE THREAD

**Issue by 8680** [NootInc/NootedRed#127]
Will it adapt to the 6800H processor in the future?

**Comment by KlavierGayming** [comment]
Check #92

**Comment by 8680** [comment]
> 检查#92 （基本上是，但不是优先事项）


Okay, thanks.

**Comment by Xryphon** [comment]
Does anyone know if you can use a supported AMD GPU (i. e. the RX 6650M) without the iGPU enabled? I have a R7 6800H and the RX 6650M but seeing as the iGPU is incompatible but my GPU is, can I still create a Hackintosh?

**Comment by Xryphon** [comment]
> @Xryphon If it has a MUX chip, you can use the dGPU.

I don't have one; am I able to disable the iGPU in the plist and use the GPU for setup, or am I stuck?

**Comment by ChefKissInc** [comment]
@Xryphon If it can’t redirect the display signal to the dGPU, then what would happen if you disabled it? :-D

**Comment by Xryphon** [comment]
@ChefKissInc I guess it could give it a try ;) but alas HP made me believe there was an actual mix switch...
