### ISSUE TITLE
System crash when running IOS simulator

### ISSUE THREAD

**Issue by dungnguyen2703** [NootInc/NootedRed#128]
**System hang then crash then login screen appear when I open IOS simulator**

**To Reproduce**
1. Open XCode
2. Create new project or open existed IOS project
3. Run project in Simulator
4. Simulator open then system hang and may be crash, then login screen appear

**Expected behavior**
It should work normally

**System Information:**
 - macOS Version: 13.4.0
 - CPU: AMD Ryzen 5 5500U
 - Mini PC Trigkey S5 with Ryzen 5 5500U

**Comment by ChefKissInc** [comment]
@dungnguyen2703 VRAM size?

**Comment by dungnguyen2703** [comment]
> @dungnguyen2703 VRAM size?

3G

**Comment by ChefKissInc** [comment]
Duplicate of #13

**Comment by truongvantuan** [comment]
> > @dungnguyen2703 VRAM size?
> 
> 3G

Hi bro, Did you get  3GB VRAM by Smokeless_UMAF method?
