### ISSUE TITLE
Can't boot in Catalina

### ISSUE THREAD

**Issue by eaccin** [NootInc/NootedRed#134]
**Kernel Panic when testing latest NootedRed.kext in Catalina (10.15.7)**
 

**To Reproduce**
1. Latest NootedRed
2. Catalina 10.15.7
3. All possible SMBIOS
4. See error in screenshot

**Expected behavior**
I've tried several SMBIOS, flags, OC parameters, drivers, etc.

**Screenshots**

![panic](https://github.com/NootInc/NootedRed/assets/8464526/2a63dae6-d521-4493-b0fe-b5dacf3dc3b5)

**System Information:**
 - macOS Version: [e.g. macOS 10.15.7]
 - CPU: [e.g. AMD Ryzen 5 5600G]

**Additional context**
Same configuration works fine in BigSur. Also, EFI works with Whatevergreen (without APU acceleration)

**Comment by ChefKissInc** [comment]
It's cut off

**Comment by eaccin** [comment]
Sorry…
![IMG_6010](https://github.com/NootInc/NootedRed/assets/8464526/fbd2af8e-e54c-4d93-8aa4-2f0d7204c740)

**Comment by ChefKissInc** [comment]
No, the panic text is what I mean. I need you to take a slow motion recording

**Comment by eaccin** [comment]
Got it, will do it

**Comment by ChefKissInc** [comment]
@eaccin (You are using the catalina branch builds and not the master branch, right...?)

**Comment by eaccin** [comment]
Hmm, yes…I was using the master 🤦‍♂️
But with the branch build I get a black screen right before booting into the OS (after verbose)
