### ISSUE TITLE
Lower Cpu performance with NootedRed kext on

### ISSUE THREAD

**Issue by KemonDream** [NootInc/NootedRed#140]
**Describe the bug**
My cpu is 5900hx and the Geekbench mark is around 8300 in both windows and macOS without the kext. But turning it on, the mark decreases to around 7300. I've also tested r23 cpu mark(13000 to 11000).
This is a weird one.
And by the way I've got a black screen and rebooting when I turned the FileVault function on.

**To Reproduce**
disable kext: mark is ok
enable kext: mark is 10% lower

**Expected behavior**
well I prefer a graphic driver not consuming that much of performance lag.
**Screenshots**

**System Information:**
 - macOS Version: 13.4.1
 - CPU: 5900hx
 - kext enabled(Lilu and vitualsmc noting else for testing)
 - acpl :cpur
**Additional context**

**Comment by ChefKissInc** [comment]
Surprise surprise, a chip that includes a GPU and CPU in the same place, performs bad under stress.

**Comment by KemonDream** [comment]
Not the gpu performance that I was reporting, it's the cpu mark.
![Screenshot 2023-07-26 at 13 12 14](https://github.com/NootInc/NootedRed/assets/104930966/6db2c502-2e57-4510-8cab-49910ad844c3)
![Screenshot 2023-07-26 at 13 14 24](https://github.com/NootInc/NootedRed/assets/104930966/799aa4b9-9ed7-472a-8e7b-321c1bb26ae0)

**Comment by ExtremeXT** [comment]
@KemonDream When your iGPU is also active, the CPU has a little less resources, hence underperforming by a bit. Benchmark scores like this usually mean nothing in the actual usage of the system.

**Comment by KemonDream** [comment]
As I said the percentage is huge and about 10-15%. I don't think a driver should cause that much of resources that I would rather not to ignore.  And also I said I tested it in windows with iGPU driver working the performance marks are in normal stage level. By the way You said the performance mark can't describe actual usage, didi you mean you have tested other application that they were in the same performance in both windows and Mac? Well anyway, thanks for the reply and hardworks on continues developing this driver.

**Comment by KemonDream** [comment]
> @KemonDream When your iGPU is also active, the CPU has a little less resources, hence underperforming by a bit. Benchmark scores like this usually mean nothing in the actual usage of the system.
As I said the percentage is huge and about 10-15%. I don't think a driver should cause that much of resources that I would rather not to ignore. And also I said I tested it in windows with iGPU driver working the performance marks are in normal stage level. By the way You said the performance mark can't describe actual usage, didi you mean you have tested other application that they were in the same performance in both windows and Mac? Well anyway, thanks for the reply and hardworks on continues developing this driver.

**Comment by ChefKissInc** [comment]
@KemonDream But NRed is not a driver. It’s a patch kext, it’s using Apple’s drivers.

**Comment by KemonDream** [comment]
Really interesting that I did a retest. The result is that the power shows in AMD CPU Gadget decreases from 65w(seated in bios PBO) to 50w when disable NRed and enable it. Well maybe it's the apple that did the trick, limiting non-apple's AMD GPU performance. or who knows
