### ISSUE TITLE
Boot failed with NootedRed in Venturare. Removing NootedRed it boots successfully.

### ISSUE THREAD

**Issue by Kaijun** [NootInc/NootedRed#144]
**Screenshots**
![0459092ed6eb87908af27d009af7ad7](https://github.com/NootInc/NootedRed/assets/1693027/4b7c2b96-78d2-4be8-9ad4-d0ca7be50f70)

![e2fb20b3e8e9510009ed7c31ff53bd5](https://github.com/NootInc/NootedRed/assets/1693027/6726cd1f-f889-4a80-8fc0-3c8f801a770f)

**System Information:**
 - macOS Version: [macOS Ventura](https://www.apple.com/hk/en/macos/ventura/)
 - CPU:  AMD Ryzen 5 5600G
 - MB: MSI Mortar B450m 
 - Connector: HDMI / DP
 - NootedRed Version: [latest](https://github.com/NootInc/NootedRed/commit/a4752d17162f19a1c8796c2b9ff8b41ce418f3f7)
 - Kexts Loaded:
    * AMDRyzenCPUPowerManagement.kext
    * AppleALC.kext
    * AppleMCEReporterDisabler.kext
    * Lilu.kext
    * RealtekRTL8111.kext
    * RestrictEvents.kext
    * SMCAMDProcessor.kext
    * VirtualSMC.kext
    * NootedRed.kext

**Additional context**
I followed the official OpenCore AMD installation guide, and the system booted successfully without any issues when NootedRed.kext was not included.

However, after adding NootedRed.kext, the system crashes and reboots after displaying logs (screenshots are available).

I'm not entirely sure about the cause of the problem. Could anyone please take a look? Thank you!

Here is my OpenCore configuration file.
https://gist.github.com/Kaijun/0c37971a44cd3040a04f82b6d4f15d02

**Comment by Kaijun** [comment]
@ChefKissInc 

sorry i forgot to attach the prerequisites information

- GCN 5 or RDNA AMD dGPU: i'm not sure what kind of type is r5-5600g, but i tried both with `wegnoegpu` or without it, it's still rebooting
- VRAM has already been set to 4GB
- Legacy Boot is also disabled
- WhateverGreen.kext is not included in my kexts
- SMBIOS i tried  iMac20,1 or iMacPro1 or MacPro7,1
- macOS version is Ventura

i'm not sure which config did i miss,  it seems that lot of r5-5600G builds have been succeeded with NootedRed

**Comment by ChefKissInc** [comment]
can't help any further because picture is of screen's corner with some numbers and memory addresses instead of the actual `panic: ...` message

**Comment by Kaijun** [comment]
> can't help any further because picture is of screen's corner with some numbers and memory addresses instead of the actual `panic: ...` message

ok let me try to grab the boot log and see what caused the panic

**Comment by ChefKissInc** [comment]
*crickets*

**Comment by amaterasushen** [comment]
I'm having the same problem

**Comment by ChefKissInc** [comment]
Timed out waiting for required information
