### ISSUE TITLE
HDMI Patches don't apply on Catalina

### ISSUE THREAD

**Issue by RionWren** [NootInc/NootedRed#147]
**Describe the bug**

**To Reproduce**
1. Use the latest version of nootedred master branch
2. Attempt to boot catalina
3. System panics practically immediately

**Expected behavior**
macOS booting 

**Screenshots**

**System Information:**
 - macOS Version: [e.g. macOS 10.15.7]
 - CPU: [e.g. AMD Ryzen 5 4500U]

**Additional context**
System boots Monterey fine.

![PXL_20230809_072121410](https://github.com/NootInc/NootedRed/assets/139723175/6febab18-edb9-49f2-8fae-2349f644f147)

**Comment by ChefKissInc** [comment]
Yes uhhh we didn't do any testing on that version with the HDMI stuff. I am aware the patches don't work there though, I'll fix it soon-ish. For now use an earlier commit

**Comment by RionWren** [comment]
Using an earlier commit does work though the same graphical artefacting I mentioned in a previous issue persists (using the add Catalina support build from 2 days ago

**Comment by ChefKissInc** [comment]
Yeah, that's what I said; that the HDMI patches don't work in Catalina.

**Comment by ChefKissInc** [comment]
[NootedRed-1.0.0-DEBUG.zip](https://github.com/NootInc/NootedRed/files/12300548/NootedRed-1.0.0-DEBUG.zip)
Can you try this? @RionWren

**Comment by RionWren** [comment]
> [NootedRed-1.0.0-DEBUG.zip](https://github.com/NootInc/NootedRed/files/12300548/NootedRed-1.0.0-DEBUG.zip) Can you try this? @RionWren

yeah sure, no worries

**Comment by RionWren** [comment]
Artefacting stays but it boots fine

**Comment by RionWren** [comment]
adding on, the last thing I mentioned in my previous issue with the artefacting still applies. If I have a monitor plugged in there is no artefacting to either the internal panel or to the display. But if its just the laptop display outputting, it artefacts. It's usable at the very least, thanks for actioning the more pressing issue so quickly!

**Comment by ChefKissInc** [comment]
@RionWren Hmmm, sounds like the (e)DP issue where the link training fails, but if you lack a dGPU and plug an HDMI monitor in before boot, that (e)DP display starts working. Very interesting!
You’re utmost welcome, btw.

**Comment by RionWren** [comment]
will do once I reinstall (was testing sonoma beta)

**Comment by RionWren** [comment]
as requested here's an ioreg with and without the secondary display attached
[Archivio.zip](https://github.com/NootInc/NootedRed/files/12326644/Archivio.zip)
both are in the zip

**Comment by RionWren** [comment]
another thing is if I disconnect the display after boot the artefacting comes back

**Comment by RionWren** [comment]
and reconnecting it goes away.

**Comment by RionWren** [comment]
> try this in ventura with no attached displays [NootedRed.kext.zip](https://github.com/NootInc/NootedRed/files/12327609/NootedRed.kext.zip)

would monterey or catalina be fine? those are the only 2 I have on this system

**Comment by RionWren** [comment]
On Catalina it just panics, on monterey I get a black screen

**Comment by RionWren** [comment]
I don't have Ventura on this system, sorry. I also don't have the storage to make a temporary partition
