### ISSUE TITLE
The system has a severe color cast, it should be blue but it shows blue-green

### ISSUE THREAD

**Issue by winktool** [NootInc/NootedRed#150]
<img width="168" alt="image" src="https://github.com/NootInc/NootedRed/assets/111169990/e61a665b-53e1-41d3-a868-419a8e86d5e5">

The system has a severe color cast, it should be blue but it shows blue-green

**Comment by ChefKissInc** [comment]
That looks like night light to me

**Comment by winktool** [comment]
close HDR works
