### ISSUE TITLE
ASUS FX505DY

### ISSUE THREAD

**Issue by Striker770** [NootInc/NootedRed#151]
Hello,

I'm having ASUS FX505DY Laptop which has AMD Ryzen 3550H CPU and RX560X (1002:67EF). I cannot drive the display from either of the GPU. The install is successful, but i cannot get display. The APU is connected to the Internal Screen and the HDMI is also connected to APU.

Any clues?

**Comment by eaglebh** [comment]
Hi @Striker770 , I have a very similar laptop, I was able to install ventura , but only get GUI without nootedred, using it I get black screen after debug messages. How have you solved your issue? I think mine is related to the driver trying to use an invalid framebuffer/connector.
