### ISSUE TITLE
Not Booting. Stuck on DSMOS Has Arrived

### ISSUE THREAD

**Issue by KikoPlays44** [NootInc/NootedRed#31]
![Screenshot_2023-03-19-20-22-05-306_com miui gallery](https://user-images.githubusercontent.com/67192357/226208445-b307519d-56fe-4eec-8547-6b0022259a1a.jpg)

**Comment by ChefKissInc** [comment]
Are you booting recovery/installer

**Comment by KikoPlays44** [comment]
No, I only added the kext after installing everything. It boots fine without it. (No hardware acceleration tho :/ )

**Comment by ChefKissInc** [comment]
Do you have Lilu 1.6.4

**Comment by KikoPlays44** [comment]
Yes

**Comment by ChefKissInc** [comment]
Join our telegram chat so we can help you: https://t.me/NootInc

**Comment by KikoPlays44** [comment]
Alright. Thanks
