### ISSUE TITLE
Cant make NootedRed wrorking with Ryzen 5 3500U

### ISSUE THREAD

**Issue by ueh-oaug** [NootInc/NootedRed#37]
hi, thank you very much cuz u was make a way for AMD Laptop

today i was try install macos on my HP Laptop but i cant make acceleration work ( it just show 7mb )
i was use Xcode build nootedRed but the kext not working. try Artifacts version in your github but it make boot conflict with Lilu.kext (lastest). still not working :(

can you give me a way to make acceleration working on my system please?

My Laptop:

CPU: Ryzen 5 3500U APU Vega 8
MAIN: HP version F.18
RAM: 8GB
SSD: Toshiba

can u spend a little time to check my issue please thank you so much. 

[EFI.zip](https://github.com/NootInc/NootedRed/files/11239007/EFI.zip)

**Comment by ChefKissInc** [comment]
@ueh-oaug You’re using WhateverGreen with NootedRed. They conflict

**Comment by ueh-oaug** [comment]
@ChefKissInc thank you for reply me. so i need remove WhateverGreen, and use NootedRed.kext in your Github Artifacts Actions right

**Comment by ChefKissInc** [comment]
@ueh-oaug Yup

**Comment by ueh-oaug** [comment]
@ChefKissInc thank you so much, i will try right now. if nothing wrong i will close this issue. thank you so much. hope u have good day!

**Comment by ChefKissInc** [comment]
@ueh-oaug You should aos

**Comment by ueh-oaug** [comment]
@ChefKissInc yes sir my hero, im trying now

**Comment by ueh-oaug** [comment]
@ChefKissInc i tried but i got stuck at here: 
![image](https://user-images.githubusercontent.com/92006941/232211956-2a9e0ad8-526b-47aa-b603-a77823df50eb.png)

its show couldn't alooc class Notered. im using kext in here: https://github.com/NootInc/NootedRed/actions/runs/4700867287

**Comment by ChefKissInc** [comment]
Are you sure you're using latest Lilu? It says it's not compatible with it

**Comment by ueh-oaug** [comment]
@ChefKissInc im sure, i'm using Lilu 1.6.4 which is latest. ill try download again

**Comment by ueh-oaug** [comment]
@ChefKissInc thank you so much!!, i had success reloading version 1.6.4 of lilu.kext. Now my system has acceleration. hope this kext will develop further, wish you success in work and life. Now I'm going to fix the rest.

**Comment by ChefKissInc** [comment]
No problem. Enjoy your accelerated system
