### ISSUE TITLE
Having trouble to modify existing SMBios.

### ISSUE THREAD

**Issue by ezxpro** [NootInc/NootedRed#40]
I have a running system where I'll need to change my current SMbios from "iMacPro1,1" to "MacPro7,1", so that it works with NootedRed. However, whenever I modify my smbios the system no longer boots. Instead of showing the Apple logo at boot, it shows a white "forbidden" sign and reboots.

I tried several times with the same result, is it even possible to do this without reinstalling everything?

Also, I have an unrelated suggestion. I saw another issue that mentions an incompatibility with whatevergreen. Maybe it would be nice to include that in the Readme.

**Comment by ChefKissInc** [comment]
@ezxpro > Maybe it would be nice to include that in the Readme. 
It already is. Literally
Also, this isn’t a support forum. If the SMBIOS change is causing issues, then your EFI is just plain bad. 
NOTE: As the README says, this kext only works in Big Sur natively. The usage of iMacPro1,1 suggests that you may be using a different version of macOS
