### ISSUE TITLE
When will we get support for 5600G and 5700G APU?

### ISSUE THREAD

**Issue by Sayor0630** [NootInc/NootedRed#44]
I have a 5600G CPU and not dGPU. Mu motherboard is Gigabyte X570S Aorus Pro AX (rev 1.1). Can i have a full configured EFI for my system? Does anyone have it?

**Comment by ExtremeXT** [comment]
@Sayor0630 Renoir APUs aren't fully supported as of now (see #11) and we don't support prebuilt EFIs, make your own with Dortania.

**Comment by ChefKissInc** [comment]
Duplicate of #11, and there's only like 4 open issues in the entire repository. Also, we're not magicians.
