### ISSUE TITLE
Ryzen 3 3200G Vega 8 Big Sur Hackintosh Doesn't See Graphics

### ISSUE THREAD

**Issue by adwaitaplus** [NootInc/NootedRed#45]
Even though I include the NootedRed plug-in in the EFI folder on the USB, it throws the black screen after the Verbose or Apple screen and does not fix it. I am trying to get image from A320M-A PRO motherboard with HDMI cable.

What is the problem?

**Comment by ChefKissInc** [comment]
Booting Recovery/Installer?

**Comment by adwaitaplus** [comment]
I am using OpenCore. @ChefKissInc

**Comment by ChefKissInc** [comment]
Thanks captain obvious
