### ISSUE TITLE
How do i inject the kext? 

### ISSUE THREAD

**Issue by vasilisfr** [NootInc/NootedRed#50]
Hi! I am new to hackintosh. As i've figured i need to transfer the aml files to the acpi folder in the efi file. and then edit the config.plist file. Do i need to transfer any files in the Kext directory in the oc folder? Thanks in advance! Hope i get a response

**Comment by vasilisfr** [comment]
I have the same processor as you, AMD Ryzen 3500u and I am trying to install macOS with no luck whatsoever, at least for the moment

**Comment by vasilisfr** [comment]
Also do i need another aml file in the ACPI folder like SSDT-USBX-etc.aml or only the two aml files provided? Thank you!

**Comment by ChefKissInc** [comment]
I think it should be pretty obvious such things are not solvable with a simple AML file
https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts
The workflow is CI. We do not have public releases as the kext is not complete yet. Please note this is not a support forum; refrain from asking questions like these (as you are polluting the bug/feature tracking)

**Comment by vasilisfr** [comment]
I am sorry! Im new to this. Is there any way to ask questions for help?

**Comment by ChefKissInc** [comment]
@vasilisfr Ask in a support forum, like AMD OS X, or our telegram group (https://t.me/NootInc)

**Comment by vasilisfr** [comment]
Thanks a lot! 👍
