### ISSUE TITLE
Tutorial on installing OSX 12+

### ISSUE THREAD

**Issue by AlphaNecron** [NootInc/NootedRed#51]
Can you add the way to downgrade kexts for newer unsupported OSX versions to the README? And will it work on AMD laptops?

**Comment by lzhoang2601** [comment]
It maked for AMD laptops. Follow https://t.me/NootInc/195265/286804 or https://github.com/ExtremeXT/APUDowngrader

**Comment by lzhoang2601** [comment]
Native with macOS Big Sur and macOS Monterey need downgrade kexts, not work with macOS version newer

**Comment by AlphaNecron** [comment]
Thanks, Ventura works?

**Comment by ExtremeXT** [comment]
@AlphaNecron It does not as of now.

**Comment by AlphaNecron** [comment]
Oh thanks.

**Comment by ChefKissInc** [comment]
These are not support forums. Go to https://t.me/NootInc
