### ISSUE TITLE
[Question] Support Lucienne ryzen 5500U

### ISSUE THREAD

**Issue by andremx20** [NootInc/NootedRed#57]
Hello and sorry for open new thread, im litte bit confuse, so i just want to ask, this update give the support for ryzen 5500U with Lucienne iGPU, thanks in advance for your effort and dedication, and one more time, sorry for make your time lost, have a grate day/night

**Comment by NyanCatTW1** [comment]
The readme literally says that it supports all Ryzen 5xxx, and I don't see how 5500 don't fall under that category
