### ISSUE TITLE
ACPI error on AMD ryzen 5 5500u nootedred kext

### ISSUE THREAD

**Issue by Berkan111111** [NootInc/NootedRed#61]
ACPI error on AMD ryzen 5 5500u nootedred kext

**Comment by ChefKissInc** [comment]
@Berkan111111 Skill issue

**Comment by Berkan111111** [comment]
Why?

**Comment by Berkan111111** [comment]
Why am I getting this error

**Comment by Berkan111111** [comment]
Laptop:Asus vivobook 15 x513ua 
Ram:8GB
![image](https://github.com/NootInc/NootedRed/assets/110422109/6c7ecd0d-fe42-42ab-b0e3-84b50f2d70cd)
EFI:https://onedrive.live.com/?authkey=%21AKM9s8sFLZPuoLY&id=83E8AF2D3EA2BA57%214076&cid=83E8AF2D3EA2BA57&parId=root&parQt=sharedby&parCid=B75E416A33C5E0B1&o=OneUp

**Comment by Berkan111111** [comment]
When Nootedred kext is added is the same error and when missing it is the same error.Can you send me an edited efi

**Comment by ChefKissInc** [comment]
If it is not specific to using NootedRed, then it is not an issue that concerns us. Please refer to a support forum like AMD OS X for installation support
