### ISSUE TITLE
black screen on recovery boot ryzen 5 4600h

### ISSUE THREAD

**Issue by ruska112** [NootInc/NootedRed#63]
[configP4.zip](https://github.com/NootInc/NootedRed/files/11582664/configP4.zip)

macos 11
cpu: amd ryzen 5 4600h (renoir iGPU)
with -wegnoegpu boot arg

If I remove the kext, everything works but with interruptions especially mouse pointer

**Comment by ChefKissInc** [comment]
Likely duplicate of #52. Verify your config is okay, then gather a dmesg and cross-reference with the details of the issue in question. If it's not, reopen the issue
