### ISSUE TITLE
On Venratu the display is backlit but not displayed

### ISSUE THREAD

**Issue by starslightbright** [NootInc/NootedRed#68]
On macos13.3.1，when I enabled this driver，the display is backlit but not displayed。Once in a while it was able to display a picture
在macos13.3.1上启用nootedred，显示屏有背光但是没有显示，偶尔才能显示一次

**Comment by starslightbright** [comment]
ventura-dbg branch

**Comment by ChefKissInc** [comment]
Ventura is not supported yet. We are doing internal testing
