### ISSUE TITLE
No Video Output After Installation

### ISSUE THREAD

**Issue by danfq** [NootInc/NootedRed#70]
**Describe the bug**
Black screen (with backlight) after verbose output - which shows no errors, or panics.
Installation was successful, with video output all the way through.
After it completed, and upon rebooting into the actual system - the bug occurs.

PC will hang in this state for a while (around 20 mins), and that's when it appears to go into sleep mode.
Upon "reviving" the PC, the behavior is as expected - except there's no backlight at all this time, and no video output as well.

**To Reproduce**
Attempt to boot system via USB, after installation.

**Expected behavior**
Expected video output to work, just like it did during the installation process.

**Screenshots**
N/A.

**System Information:**
 - macOS Version: Monterey (Latest from OpenCore).
 - CPU: AMD Ryzen 5 5600G.
 - GPU: None (RTX 3060Ti - disabled via boot-arg).
 - RAM: 32GB.

**Additional context**
N/A.

**Comment by ChefKissInc** [comment]
@danfq Do you mean... the last stage of installation?

**Comment by ChefKissInc** [comment]
@danfq Nope, you are at the installation finalisation stage that’s right before that. Lilu has a bug and does not detect it as recoveryOS, therefore, we can’t do anything about it. For now, disable NRed for that step to complete and then enable it back

**Comment by danfq** [comment]
@ChefKissInc 

If I disable NRed, I won't have output, right?
Or would I still be able to move forward with VESA?

**Comment by ChefKissInc** [comment]
@danfq Latter

**Comment by danfq** [comment]
@ChefKissInc 

So, I tried that - and completed setup with no issues, in VESA mode.
The problem remains after re-enabling NRed.

Any other ideas?

**Comment by ChefKissInc** [comment]
> @ChefKissInc 
> 
> 
> 
> So, I tried that - and completed setup with no issues, in VESA mode.
> 
> The problem remains after re-enabling NRed.
> 
> 
> 
> Any other ideas?

Which SMBIOS are you using?

**Comment by danfq** [comment]
> > @ChefKissInc
> > So, I tried that - and completed setup with no issues, in VESA mode.
> > The problem remains after re-enabling NRed.
> > Any other ideas?
> 
> Which SMBIOS are you using?

As mentioned in the README: MacPro7,1

**Comment by ChefKissInc** [comment]
@danfq We have heard from some users that it causes a black screen for some obscure issue, can you try iMacPro1,1 or MacBookPro16,3?

**Comment by danfq** [comment]
> @danfq We have heard from some users that it causes a black screen for some obscure reason, can you try iMacPro1,1 or MacBookPro16,3?

No luck with iMacPro1,1.
MacBookPro16,3 worked!

I can now boot and I have full graphics acceleration, with 4GB of VRAM!

Thank you so much!

**Comment by ChefKissInc** [comment]
@danfq No problem! Enjoy
