### ISSUE TITLE
Black screen on Ryzen 5 PRO 3350G (GA-A320M-H) over VGA

### ISSUE THREAD

**Issue by binxr** [NootInc/NootedRed#73]
amd ryzen 5 3350gPRO
vega 11
a320m-h 

well, i install the kext and appears a black screen when i boot up the mac os

**Comment by Allen050329** [comment]
@binxr Using HDMI?

**Comment by binxr** [comment]
@Allen050329 using vga bro!

**Comment by Allen050329** [comment]
Bruh, VGA support has been long removed from macOS

**Comment by binxr** [comment]
yo, seriously?

**Comment by NyanCatTW1** [comment]
https://elitemacx86.com/threads/vga-output-not-working-in-macos-big-sur.1064/
> VGA is generally not supported on macOS/OS X. It mostly works on Laptops due to being a DP connection internally. For Desktops, use VGA to HDMI cable/Adapter.
