### ISSUE TITLE
HDMI Black Screen

### ISSUE THREAD

**Issue by binxr** [NootInc/NootedRed#75]
Hello again! I use the kext (also very good) but i restart my pc and there are showing me a black screen, in  HDMI

R5 3350gPRO
VEGA 11
A320MH

**Comment by ChefKissInc** [comment]
@binxr

- Big Sur or Monterey (**no** Ventura or Catalina, they are experimental),
- SMBIOS `MacPro7,1`, `iMac20,1` or `MacBookPro16,3`,
- **No** `WhateverGreen`,
- Increased **VRAM Size** to **512MB+**,
etc?

**Comment by binxr** [comment]
@ChefKissInc  Monterey 
im using mac pro late 2013. i think it was MacPro6.1
no whatevergreen
2gb vram

**Comment by ChefKissInc** [comment]
Change SMBIOS

**Comment by binxr** [comment]
that probably will resolve this problem?

**Comment by ChefKissInc** [comment]
@binxr It can. No guarantees

**Comment by binxr** [comment]
ok ill do it

**Comment by binxr** [comment]
@ChefKissInc It worked! thank you so much!

**Comment by ChefKissInc** [comment]
That's great. Enjoy!

**Comment by ChefKissInc** [comment]
@lucasolegario English only please. Also, you don’t need to reinstall macOS when changing serials, only to sign out of iCloud beforehand and reset NVRAM before booting after the change

**Comment by lucasolegario** [comment]
@ChefKissInc thank you

**Comment by binxr** [comment]
> @binxr ao alterar o SMBIOS você reinstalou ou só inicializou pelo pen driva com a EFI atualizada?

i initializate on pendrive bro
