### ISSUE TITLE
HDMI Audio not functional

### ISSUE THREAD

**Issue by womengzouzailushang** [NootInc/NootedRed#76]
已定制声卡，连接音箱可以正常播放音频；但是通过HDMI外接电视等设备时，没有识别到有HDMI音频设备；请问有何解决方式，总不能和Intel核显一样定制HDMI吧，

**Comment by NyanCatTW1** [comment]
抱歉，此问题不在 NootedRed 功能范围内。建议您可以研究 AppleALC 和其他音频驱动方式。

**Comment by ChefKissInc** [comment]
After further investigation it appears AppleGFXHDA might need to attach to the HDAU device, and it seems to do so by PCI device ID matching. We're investigating, but hopefully all that's needed is a new personality embedded in NRed

**Comment by ChefKissInc** [comment]
Never can I, I have NC and Allen as my translators lol. But that's fair. The issue is basically that the HDMI Audio is not recognised

**Comment by shuhung97** [comment]
My 5600g HDMI (D015) port work with VoodooHDA 3.0.2 on Monterey, need boot from recovery and disable SIP, sound is good, now test Ventura but seems to be hard to disable SIP.
![image](https://github.com/NootInc/NootedRed/assets/132800063/6eb41b89-e069-40b3-845f-71f9e87d1867)

**Comment by ChefKissInc** [comment]
We do not approve the use of VoodooHDA or disabling security features under any circumstances.

**Comment by ChefKissInc** [comment]
![IMAGE 2023-06-20 00:53:06](https://github.com/NootInc/NootedRed/assets/30368284/e017ca2a-af08-4790-9408-19e9fd0563e9)
We made some progress, but there's no sound playing

**Comment by ChefKissInc** [comment]
@jalavoui I tested this and it fixed nothing. It is likely VHDA interfering with your setup

**Comment by ChefKissInc** [comment]
(Note: Test was conducted by @ExtremeXT on Renoir)

**Comment by womengzouzailushang** [comment]
Has HDMI audio been fixed because I saw an HDMI branch: 'Add HDMI audio support'?

**Comment by ChefKissInc** [comment]
@womengzouzailushang Works for most people, doesn’t for others

**Comment by ChefKissInc** [comment]
So, have you tried it yet? @womengzouzailushang
