### ISSUE TITLE
Boot Process is getting stuck at "Registered CoreAnalyticsHub functions with xnu."

### ISSUE THREAD

**Issue by DevFelixLiS** [NootInc/NootedRed#78]
Made an hackintosh with the opencore guide, implemented NootedRed and started booting. 

System Information:
 - macOS Version: 12.6.6
 - CPU: Ryzen 7 5825U
 
https://files.nocx420.xyz/tqkfsBaJ.jpeg

**Comment by DevFelixLiS** [comment]
Let me know if more informations are needed.

**Comment by DevFelixLiS** [comment]
Reddit Post: https://www.reddit.com/r/hackintosh/comments/13wgswi/stuck_at_registered_coreanalyticshub_functions/

**Comment by ChefKissInc** [comment]
Does it boot without NRed

**Comment by DevFelixLiS** [comment]
Nope. 
Maybe not because there is no kext for graphics in it.

**Comment by ChefKissInc** [comment]
macOS can boot with VESA graphics. As your set up cannot boot even with the kext disabled, the problem is not related to NRed. Closing this issue
