### ISSUE TITLE
The external monitor of the laptop cannot output signals normally

### ISSUE THREAD

**Issue by bobouncle** [NootInc/NootedRed#79]
CPU is 5800H Monterey.12.5, connected to the monitor through TYPC-C to HDMI, the screen no signal output. Is it currently not supported to use laptop external monitors?

**Comment by ChefKissInc** [comment]
English.

**Comment by ChefKissInc** [comment]
Does your system have a dGPU?

**Comment by ChefKissInc** [comment]
@bobouncle

**Comment by cmd2001** [comment]
> Does your system have a dGPU?

Lenovo R9000X comes with a Nvidia dGPU, and in most of cases the video output of a gaming laptop is directly connected to dGPU.

In another word, the video output such as HDMI and Type-C would NEVER work under macOS.

**Comment by ChefKissInc** [comment]
He did not specify what system this is running on, only the processor

**Comment by cmd2001** [comment]
> He did not specify what system this is running on, only the processor

In fact he did specify his system in the original Chinese version.

```
笔记本是联想的R9000X CPU是5800H，通过TYPC-C HDMI 连接显示器时，屏幕黑屏无信号输出。目前是不支持笔记本外接显示器使用吗？
```

In English, it means:

```
My laptop is Lenovo R9000X whose GPU is 5800H. I got black screen when trying to connect my monitor through Type-C or HDMI. Is it supported to connect external display with laptop?
```

**Comment by ChefKissInc** [comment]
Oh, I did not see that. With that in mind, the issue can be closed as the port is wired to the unsupported dGPU. Thanks.
