### ISSUE TITLE
Unstable kext (BIOSTAR A320MH)

### ISSUE THREAD

**Issue by binxr** [NootInc/NootedRed#80]
I'm having some problems with my vega 11, the efi is within compliance. and I'm running on mac os monterey, it works, but when it boots, it stays on a black screen, if you want I can send the EFI

BIOSTAR A320MH
AMD Ryzen 5 3350gPRO with vega graphics (vega 11)

**Comment by binxr** [comment]
kext works normally only once in a while

**Comment by ChefKissInc** [comment]
Which branch?

**Comment by binxr** [comment]
if you're talking about kext, the newest

**Comment by ChefKissInc** [comment]
@binxr There’s no just “newest”. There’s master, add-ventura-support, add-catalina-support, ventura-dbg, catalina-dbg

**Comment by binxr** [comment]
sorry, add catalina support is the correct branch

**Comment by ChefKissInc** [comment]
@binxr Why are you using the catalina branch for Monterey

**Comment by binxr** [comment]
true, excuse my stupidity

**Comment by binxr** [comment]
you can say me the correct one?

**Comment by ChefKissInc** [comment]
@binxr master

**Comment by binxr** [comment]
kernel panic LMAO

**Comment by ChefKissInc** [comment]
@binxr Wat

**Comment by ChefKissInc** [comment]
@binxr Show it?
