### ISSUE TITLE
STUCK AT: ACPI ERROR: [\_SB_.PCI0.GP18.SATA] - Lenovo ideapad slim 5 pro

### ISSUE THREAD

**Issue by ueh-oaug** [NootInc/NootedRed#82]
hi, hope u have good day..

i am extremely happy that you make this kext for AMD laptop. and today, i tried to install it on my laptop.

My laptop specs:

Lenovo ideapad slim 5 pro
CPU: Ryzen 7 5800H - 8 core
RAM: 16GB
SSD: SN750
WIFI: unsupported

i try to install Monterey with your lastest Artifacts kext in Action Part but i cant make my laptop bootable. i stuck at ACPI error: STUCK AT: ACPI ERROR: [\_SB_.PCI0.GP18.SATA] . do you know to fix this error?. please help me. thank you very much. 

![345468025_822437196213959_3410009618828293425_n](https://github.com/NootInc/NootedRed/assets/92006941/ad776aa5-4d28-4bd1-b791-ea5048332294)

Here is my EFI: 
[EFI.zip](https://github.com/NootInc/NootedRed/files/11678847/EFI.zip)

**Comment by ChefKissInc** [comment]
@ueh-oaug

**Comment by ueh-oaug** [comment]
@ChefKissInc thank you for reply, althought disable it, i still got this error: 

![image](https://github.com/NootInc/NootedRed/assets/92006941/d6de1e2e-8893-47c7-9c78-cfdaef0f98fe)

**Comment by ueh-oaug** [comment]
Bios doesn't have much to set, I set the same as the dortania guide.

**Comment by ueh-oaug** [comment]
@ChefKissInc thank you, I will look for public help, it seems that AMD Laptop is still too new, no one can help me :(

**Comment by ChefKissInc** [comment]
@ueh-oaug Our telegram group is https://t.me/NootInc. The issues are for NRed itself
