### ISSUE TITLE
OLED screen

### ISSUE THREAD

**Issue by baisong57** [NootInc/NootedRed#83]
**Describe the bug**
My laptop has an OLED screen, and after loading the corresponding kernel and patch, I found that although I can drag the brightness bar when HDR is turned off, the brightness has not actually changed. When HDR is turned on, not only can automatic brightness be used to adjust it, but manual adjustment can also be used, but the problem is that the screen will keep flashing at this time. When I adjust the screen brightness and want to turn off HDR, the screen brightness will not remain unchanged, but will automatically adjust to the maximum value again.

**System Information:**
 - macOS Version: [e.g. macOS 11.7.7]
 - CPU: [e.g. AMD Ryzen 5 5600H]

**Additional context**
LCD Screen is normal.

**Comment by ExtremeXT** [comment]
@baisong57 macOS does not support OLED screen backlight level changing, there was no Mac that came with one, you can try using a third-party app like Lunar or MonitorControl.
