### ISSUE TITLE
Ryzen 5 3400G

### ISSUE THREAD

**Issue by JeanxPereira** [NootInc/NootedRed#86]
**Describe the bug**
I have attempted to create the EFI folder multiple times with different builds of NootedRed, but without success. The only time it worked was with an older build and the bootarg -nredfbonly, but even then, graphics acceleration did not function correctly. Whenever I disable it, the system boots up. However, I've noticed other users experiencing similar issues; they can only boot with a meager 7MB dedicated to the graphics card.

**Screenshots**
This is the latest log from my attempts, i have more screenshots
![Image description](https://cdn.discordapp.com/attachments/686886928641032246/1116409939859095622/PXL_20230608_135353847.jpg)

**System Information:**
 - **macOS Version:** macOS Monterey 12.3
 - **CPU:** AMD Ryzen 5 3400G
 - **MOBO:** Asus EX-A320M-GAMING
 - **RAM:** Kingston HyperX Fury 16 GB (2 x 8 GB) DDR4-2666

**Additional context**
https://www.reddit.com/r/Ryzentosh/comments/125h64p/7mb_graphics_3400g/

[My config.plist](https://raw.githubusercontent.com/JeanxPereira/GPTStuff/main/config.plist?token=GHSAT0AAAAAAB6N26LDBPOMEQKHECSPV4VUZEDQNDQ)

**Comment by ExtremeXT** [comment]
@JeanxPereira The Issues page is intended for bugs in the kext, not for support with creating your EFI folder. For this, you can ask in a support forum that supports AMD APUs, like AMD OS X (Discord) or even the [Noot Telegram Supergroup](https://t.me/NootInc).

**Comment by JeanxPereira** [comment]
thank you
