### ISSUE TITLE
Chromium browsers crash and Black Screen

### ISSUE THREAD

**Issue by AlexSmArs** [NootInc/NootedRed#91]
I'm having a problem with chromium browser freezing then crashing system and sometimes telegram, I tried whatevergreen for test it's working well but when I turn on nootedred it crashes. And I use SMClightsensor because I get black screen. 
My specs: -AMD Ryzen 3 3200g 
- Motherboard: Prime A320M-K
- AMD Radeon Vega 8 
- 16Gb (2666MHz)
Ventura 13.4 same issue was on BigSur 
Saw people with similar specs having the same problem. I can send EFI if needed 
And weird red line before chrome crashing system 
![photo_2023-06-12_22-27-55](https://github.com/NootInc/NootedRed/assets/135840603/33662319-166b-4d3e-b282-d4c0b2e6d90d)

**Comment by ExtremeXT** [comment]
@AlexSmArs Known issue - Chromium browsers have artifacts and/or crash the system. A workaround is to disable GPU rastorazation, but we recommend just using Safari for full GPU rendering of websites. For the black screen, you can try using iMac20,1 SMBIOS instead of MacPro7,1.

**Comment by AlexSmArs** [comment]
> @AlexSmArs Known issue - Chromium browsers have artifacts and/or crash the system. A workaround is to disable GPU rastorazation, but we recommend just using Safari for full GPU rendering of websites. For the black screen, you can try using iMac20,1 SMBIOS instead of MacPro7,1.

Okay, thank you for advice i'll try, i hope it will be fixed
