### ISSUE TITLE
unstable kext (A320MH-BIOSTAR RYZEN 5 3350GPRO VEGA 11)

### ISSUE THREAD

**Issue by binxr** [NootInc/NootedRed#99]
well, I don't know why but there is a black screen with the kext almost every time I start MacOS, but sometimes it works and recognizes my video card, that's very strange.
if the problem is the version of nootedred that I'm using, please tell me the right one.

i'm using the latest version that not marked with NOT USE, (catalina support)

**Comment by binxr** [comment]
@ChefKissInc in the case allocateHWEngines wrap is the right one? is marked with master

**Comment by ChefKissInc** [comment]
@binxr Yes

**Comment by binxr** [comment]
@ChefKissInc if this was my solution i'll cry haha

**Comment by binxr** [comment]
@ChefKissInc black screen again after put the right one in EFI

**Comment by ChefKissInc** [comment]
@binxr Which macOS version are you using?

**Comment by binxr** [comment]
@ChefKissInc monterey man

**Comment by ChefKissInc** [comment]
@binxr And the SMBIOS?

**Comment by binxr** [comment]
@ChefKissInc MacPro7,1

**Comment by ChefKissInc** [comment]
@binxr MacPro7,1 has black screen issues as per the README. If you want to help us debug, we’ll need logs. The process is slightly involved and time consuming. If you don’t want to indulge in it, try iMac20,1

**Comment by binxr** [comment]
@ChefKissInc i'll try iMac20,1 first, my gmt-3 says thats 5:57am

**Comment by binxr** [comment]
@ChefKissInc bro, i reboot 3 times and right off the bat it worked, if i have any problem i'll back here to explain bye and thank you!
